bases:
- ../../base

images:
- name: redroid/redroid
  newTag: 9.0.0-latest

patches:
- target:
    kind: StatefulSet
  patch: |-
    - op: replace
      path: /metadata/name
      value: redroid9
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/selector/matchLabels/app
      value: redroid9
    - op: replace
      path: /spec/template/metadata/labels/app
      value: redroid9
